//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ModuleManager.rc 使用
//
#define IDC_SERVICE_ATTRIB              3
#define IDD_SERVER_ITEM                 129
#define IDD_DIALOG_TABLE_CONFIG         130
#define IDD_SERVER_WIZARD_MAIN          137
#define IDD_SERVER_OPTION_1             148
#define IDD_SERVER_WIZARD_1             150
#define IDD_SERVER_OPTION_3             151
#define IDC_LOAD_SERVER                 1000
#define IDC_SERVER_NAME                 1001
#define IDC_LIST                        1001
#define IDC_MODULE_LIST                 1002
#define IDC_BTN_ADD                     1002
#define IDC_BTN_DELETE                  1003
#define IDC_STATIC_HINT                 1004
#define IDC_EDIT1                       1005
#define IDC_EDIT2                       1006
#define IDC_NODE_ID                     1007
#define IDC_EDIT3                       1007
#define IDC_SERVER_TYPE                 1008
#define IDC_EDIT4                       1008
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_EDIT_NORMAL_PIC             1009
#define IDC_TABLE_COUNT                 1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_MAX_PLAYER                  1011
#define IDC_EDIT5                       1011
#define IDC_SERVER_PORT                 1012
#define IDC_SERVER_LIST                 1012
#define IDC_EDIT6                       1012
#define IDC_EDIT_PLAYING_PIC            1012
#define IDC_SORT_ID                     1013
#define IDC_EDIT7                       1013
#define IDC_CELL_SCORE                  1014
#define IDC_RELOAD_LIST                 1014
#define IDC_MODULE_DESCRIBE             1014
#define IDC_EDIT8                       1014
#define IDC_EDIT9                       1015
#define IDC_CHAIR_COUNT                 1016
#define IDC_MAX_ENTER_MEMBER7           1016
#define IDC_EDIT10                      1016
#define IDC_DATABASE_ADDR               1017
#define IDC_EDIT11                      1017
#define IDC_MAX_GAME_TIME               1017
#define IDC_DELETE_SERVER               1018
#define IDC_DATABASE_NAME               1018
#define IDC_EDIT_TABLENAME              1018
#define IDC_EDIT12                      1019
#define IDC_SERVICE_DLL_NAME            1021
#define IDC_KIND_ID                     1022
#define IDC_CLIENT_EXE_NAME             1023
#define IDC_GAME_NAME                   1024
#define IDC_RESTRICT_SCORE              1026
#define IDC_REVENUE_RATIO               1027
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_REVENUE_RADIO               1027
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_SERVICE_REVENUE             1028
#define IDC_SERVICE_SCORE               1028
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_AV_SERVER_PORT              1031
#define IDC_LAST                        1065
#define IDC_NEXT                        1067
#define IDC_ITEM_FRAME                  1072
#define IDC_FINISH                      1076
#define IDC_PROMPT                      9000
#define IDD_SERVER_OPTION_2             9001
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDD_SERVER_WIZARD_2             9002
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDD_SERVER_OPTION_4             9003
#define IDC_FORFEND_ROOM_CHAT           9004
#define IDC_FORFEND_WISPER_CHAT         9005
#define IDD_SERVER_OPTION_5             9005
#define IDC_FORFEND_GAME_CHAT           9006
#define IDD_SERVER_MATCH                9006
#define IDC_ALLOW_DYNAMIC_JOIN          9007
#define IDD_DIALOG_TABLE                9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDC_ALLOW_OFFLINE_TRUSTEE       9010
#define IDC_ALLOW_AVERT_CHEAT_MODE      9011
#define IDC_ALLOW_ANDROID_ATTEND        9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_TAB_CTRL                    9015
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_FORFEND_LOCK_TABLE          9016
#define IDC_FORFEND_SAVE_IN_GAME        9017
#define IDC_FORFEND_SAVE_IN_ROOM        9018
#define IDC_ALLOW_ANDROID_SIMULATE      9019
#define IDC_FORFEND_TAKE_IN_ROOM        9020
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDC_GAME_ID                     9021
#define IDC_DISTRIBUTE_ALLOW            9022
#define IDC_STATIC_REVENUE_SERVICE      9022
#define IDC_FORFEND_TAKE_IN_GAME        9022
#define IDC_DISTRIBUTE_LAST_TABLE       9023
#define IDC_FORFEND_TRANSFER_IN_ROOM    9023
#define IDC_DISTRIBUTE_IMMEDIATE        9024
#define IDC_RADIO2                      9024
#define IDC_SERVICE_RADIO               9024
#define IDC_FORFEND_TAKE_IN_ROOM3       9024
#define IDC_FORFEND_TRANSFER_IN_GAME    9024
#define IDC_MIN_DISTRIBUTE_USER         9025
#define IDC_FORFEND_CALCULATE_BALANCE_SCORE 9025
#define IDC_MAX_DISTRIBUTE_USER         9026
#define IDC_FORFEND_CALCULATE_BALANCE_SCORE2 9026
#define IDC_FORFEND_GET_BALANCE_SCORE   9026
#define IDC_DISTRIBUTE_TIME_SPACE       9027
#define IDC_ALLOW_OFFLINE_TRUSTEE2      9027
#define IDC_ALLOW_TRUSTEE_WRITESCORE    9027
#define IDC_DISTRIBUTE_DRAW_COUNT       9028
#define IDC_DISTRIBUTE_SAME_ADDRESS     9029
#define IDC_DISTRIBUTE_START_DELAY      9030
#define IDC_LIST2                       9033
#define IDC_DATETIMEPICKER_START_DATE   9034
#define IDC_DATETIMEPICKER_END_DATE     9035
#define IDC_TIME_INTERVAL               9036
#define IDC_SQUARE_SORT_TYPE            9037
#define IDC_SQUAREMATCH_NAME            9039
#define IDC_TIME_INTERVAL3              9040
#define IDC_RANK_NUMBER                 9040
#define IDC_SQUAREMATCH_DESC            9041
#define IDC_DATETIMEPICKER_START_TIME   9043
#define IDC_EDIT_MATCHNAME              9044
#define IDC_DATETIMEPICKER_END_TIME     9044
#define IDC_START_SQUAREMATCH           9046
#define IDC_BUTTON1                     9048
#define IDC_BTN_TABLE_OPTION            9048
#define IDC_BUTTON_CUSTOM_RULE          9048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9005
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9049
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
